/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Code.Cadastrar;
import Code.Useful;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author willi
 */
public class NovaConta extends javax.swing.JFrame {

    /**
     * Creates new form NovaConta
     */
    public NovaConta() {
        this.getContentPane().setBackground(new Color(102, 102, 102));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelAdicionarNovaConta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jFormattedTextFieldDia = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMes = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAno = new javax.swing.JFormattedTextField();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldValorCents = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        jLabelAdicionarNovaConta.setFont(new java.awt.Font("Rounded Elegance", 0, 36)); // NOI18N
        jLabelAdicionarNovaConta.setText("Adicionar Nova Conta");

        jLabel1.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel1.setText("Valor:");

        jLabel2.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel2.setText("Vencimento:");

        jLabel3.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel3.setText("Status:");

        jLabel4.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel4.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel5.setText(",");

        jLabel7.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel7.setText("/");

        jLabel8.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jLabel8.setText("/");

        jTextFieldStatus.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N
        jTextFieldStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));

        jTextFieldTipo.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N
        jTextFieldTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });

        jButtonCadastrar.setFont(new java.awt.Font("Rounded Elegance", 0, 18)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jFormattedTextFieldDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));
        try {
            jFormattedTextFieldDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldDia.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N

        jFormattedTextFieldMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));
        try {
            jFormattedTextFieldMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldMes.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N

        jFormattedTextFieldAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));
        try {
            jFormattedTextFieldAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldAno.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N

        jFormattedTextFieldValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));
        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldValor.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N

        jFormattedTextFieldValorCents.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 175, 165)));
        jFormattedTextFieldValorCents.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldValorCents.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldValorCents.setFont(new java.awt.Font("Rounded Elegance", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAdicionarNovaConta))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldAno, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                            .addComponent(jTextFieldStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldValorCents))
                            .addComponent(jTextFieldTipo))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelAdicionarNovaConta)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jFormattedTextFieldValorCents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCadastrar, jFormattedTextFieldAno, jFormattedTextFieldDia, jFormattedTextFieldMes, jFormattedTextFieldValor, jFormattedTextFieldValorCents, jTextFieldStatus, jTextFieldTipo});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Cadastrar cad = new Cadastrar();
        Useful use = new Useful();

        if (verifyAll()) {
            JOptionPane.showMessageDialog(null, "preencha os campos em vermelhos", "Insert", INFORMATION_MESSAGE, null);
        } else {
            String valor = this.valorUnificado(this.jFormattedTextFieldValor.getText(), this.jFormattedTextFieldValorCents.getText());
            String tipo = this.jTextFieldTipo.getText();
            String vencimento = use.dateFormat(this.jFormattedTextFieldDia.getText(), this.jFormattedTextFieldMes.getText(), this.jFormattedTextFieldAno.getText(), "us");
            String status = this.jTextFieldStatus.getText();
            
            try {
                cad.novaConta(valor, tipo, vencimento, status);
            } catch (ClassNotFoundException | SQLException ex ) {
                JOptionPane.showMessageDialog(null, "Não foi possível adcionar a nova conta devido ao segunte erro:/n"+ex, "Erro ao cadastrar", INFORMATION_MESSAGE, null);
            } 
             
            
            
        }

    }//GEN-LAST:event_jButtonCadastrarActionPerformed
    private String valorUnificado(String a, String b) {
        return "R$" + a + "," + b;
    }

    private boolean verifyAll() {
        Useful u = new Useful();
        boolean booValor = true, booCentavos = true, booTipo = true, booDia = true, booMes = true, booAno = true, booStatus = true;
        booValor = u.validateField(this.jFormattedTextFieldValor);
        booCentavos = u.validateField(this.jFormattedTextFieldValorCents);
        booTipo = u.validateField(this.jTextFieldTipo);
        booDia = u.validateField(this.jFormattedTextFieldDia);
        booMes = u.validateField(this.jFormattedTextFieldMes);
        booAno = u.validateField(this.jFormattedTextFieldAno);
        booStatus = u.validateField(this.jTextFieldStatus);
        return !(booValor || booCentavos || booTipo || booDia || booMes || booAno || booStatus);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextFieldAno;
    private javax.swing.JFormattedTextField jFormattedTextFieldDia;
    private javax.swing.JFormattedTextField jFormattedTextFieldMes;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorCents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAdicionarNovaConta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
